---

- name: Push
  shell: git push upstream v{{release_version}}
  args:
    chdir: '{{github_folder}}/{{github_repository}}'

- name: Push
  shell: git checkout main && git push upstream main
  args:
    chdir: '{{github_folder}}/{{github_repository}}'
